# Sonof iFan03 controller in spare room
#
substitutions:
  device_id: spare_room_ceiling
  device_name: Spare Room Ceiling Fan
  static_ip: 192.168.10.32
  log_level: info

esphome:
  name: $device_id
  platform: ESP8266
  board: esp8285
  includes:
    - ifan03.h
  on_boot:
    priority: 225
    # turn off the light as early as possible
    then:
      - light.turn_off: ${device_id}_light

<<: !include common/common.yaml

binary_sensor:
  - platform: gpio
    id: ${device_id}_vbutton_light
    pin:
      number: GPIO0
      inverted: True
    on_press:
      then:
        - light.toggle: ${device_id}_light

  - platform: gpio
    id: ${device_id}_vbutton_relay_1
    pin:
      number: GPIO9
      inverted: True
    on_press:
      then:
        - switch.toggle: ${device_id}_fan_relay1
        - switch.turn_on: ${device_id}_update_fan_speed

  - platform: gpio
    id: ${device_id}_vbutton_relay_2
    pin:
      number: GPIO10
      inverted: True
    on_press:
      then:
        - switch.toggle: ${device_id}_fan_relay2
        - switch.turn_on: ${device_id}_update_fan_speed

  - platform: gpio
    id: ${device_id}_vbutton_relay_3
    pin:
      number: GPIO14
      inverted: True
    on_press:
      then:
        - switch.toggle: ${device_id}_fan_relay3
        - switch.turn_on: ${device_id}_update_fan_speed

output:
  - platform: custom
    type: float
    outputs:
      id: ${device_id}_fanoutput
    lambda: |-
      auto fan = new IFan03Output();
      App.register_component(fan);
      return {fan};

  - platform: gpio
    pin: GPIO12
    id: ${device_id}_lightoutput

light:
  - platform: binary
    name: "${device_name} Light"
    output: ${device_id}_lightoutput
    id: ${device_id}_light

switch:
  - platform: template
    id: ${device_id}_update_fan_speed
    optimistic: True
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition:
              and:
                - switch.is_off: ${device_id}_fan_relay1
                - switch.is_off: ${device_id}_fan_relay2
                - switch.is_off: ${device_id}_fan_relay3
            then:
              - fan.turn_off: ${device_id}_fan
        - if:
            condition:
              and:
                - switch.is_on: ${device_id}_fan_relay1
                - switch.is_off: ${device_id}_fan_relay2
                - switch.is_off: ${device_id}_fan_relay3
            then:
              - fan.turn_on:
                  id: ${device_id}_fan
                  speed: LOW
        - if:
            condition:
              and:
                - switch.is_on: ${device_id}_fan_relay1
                - switch.is_on: ${device_id}_fan_relay2
                - switch.is_off: ${device_id}_fan_relay3
            then:
              - fan.turn_on:
                  id: ${device_id}_fan
                  speed: MEDIUM
        - if:
            condition:
              and:
                - switch.is_on: ${device_id}_fan_relay1
                - switch.is_off: ${device_id}_fan_relay2
                - switch.is_on: ${device_id}_fan_relay3
            then:
              - fan.turn_on:
                  id: ${device_id}_fan
                  speed: HIGH
        - switch.turn_off: ${device_id}_update_fan_speed

  - platform: gpio
    pin: GPIO5
    id: ${device_id}_fan_relay1

  - platform: gpio
    pin: GPIO4
    id: ${device_id}_fan_relay2

  - platform: gpio
    pin: GPIO15
    id: ${device_id}_fan_relay3

fan:
  - platform: speed
    output: ${device_id}_fanoutput
    id: ${device_id}_fan
    name: "${device_name} Fan"
