---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  name: Prusa
  id: sonoff_s31_03

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor.yaml
